feat: Oauth register/login implementation
lenra-io/client-common pull request #88
Opened 2023-07-05 14:13 UTC by jonas-martinez

Closes https://github.com/lenra-io/client-common/issues/82

## Description of the changes

Implementation of the oauth register/login methods.
For the moment, we will be using the `url_launcher` library to redirect to the oauth authentication page.
It is possible to use the `webview_flutter` library for Android and IOS but this might need some research to make sure that there is no problem using it with Hydra.

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

## Technical highlight/advice

2023-07-17 13:21 UTC, jonas-martinez commented on lib/views/auth/oauth_page.dart
> +                // TODO: Update the role of the user
@taorepoara @Nesqwik How do we want to update the role of the user with the oauth system? Should it be done in the consent process of oauth (CGUs could differ between client and backoffice) or should it be done in the backoffice by maybe keeping the validation dev page?

2023-07-19 14:25 UTC, jonas-martinez commented
I still need to find a way to check if the user is authenticated without running the `authenticate` function that opens the popup.

2023-07-19 15:31 UTC, jonas-martinez commented
When I try to connect to the oauth with a bad access_token (from another hydra client for example), I get this error
 ```
Request: GET /api/me/opened_apps
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined
        nil.id()
        (lenra_web 0.1.0) lib/lenra_web/plug/verify_cgu.ex:14: LenraWeb.Plug.VerifyCgu.call/2
        (lenra_web 0.1.0) LenraWeb.Router.ensure_cgu_accepted/2
        (lenra_web 0.1.0) lib/lenra_web/router.ex:1:
...
```
 
The `current_resource` method returns `nil` for the user

2023-08-08 07:38 UTC, Nesqwik commented
@jonas-martinez how is it going ? Do you need help ? :)

2023-08-08 07:49 UTC, jonas-martinez commented
@Nesqwik I'm doing a lot of rework because there was too much problems with the error handling. I'm working on another issue for the moment but I expect to finish this feature before the end of the week.

2023-08-14 14:59 UTC, taorepoara requested changes
Some little comments.

2023-08-14 14:59 UTC, taorepoara commented on lib/navigator/guard.dart
> +  Future<bool> Function(BuildContext, Map<String, dynamic>?) isValid;
What is the metadata param  made for ?

It does not seems to be used...

2023-08-14 16:51 UTC, jonas-martinez commented on lib/navigator/common_navigator.dart
>    static GoRoute changeLostPassword = GoRoute(
FIxed it

2023-08-16 08:30 UTC, taorepoara approved these changes

2023-08-16 08:41 UTC, merged

2023-08-16 08:42 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.45 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/client-common/releases/tag/v1.0.0-beta.45)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: